### ISSUE TITLE
Linking images and stylesheets

### ISSUE THREAD

**Issue by Default4152** [wesf76/prj-rev-bwfs-dasmoto#1]
Important for errors - The stylesheet and images are linked incorrectly to function properly on all computers. I would recommend using the following instead:
* `<link rel="stylesheet" type="text/css" href="../resources/style.css">`
* `<img src="../resources/hacksaw.jpeg"/>`
* `<img src="../resources/frames.jpeg"/>`
* `<img src="../resources/finnish.jpeg">`

This tells it to go up one directory and into the resources folder.

**Comment by wesf76** [comment]
Got it thank you for your feedback.
